name: Flask App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install -r requirements.txt

      # Step 4: Run unit tests
      - name: Run unit tests
        run: |
          python3 -m unittest discover -s tests -p "test*.py"

      # Step 5: Deploy to EC2 Instance via SSH with Password Authentication
      - name: Deploy to EC2 Instance
        run: |
          sshpass -p ${{ secrets.EC2_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ ec2-user }}@${{ secrets.EC2_PUBLIC_IP }} << EOF
          cd ~/ForestFire/
          git pull origin main
          python3 app.py &
          EOF
